name: Formatting and linting

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Run formatting and lint checks
        run: yarn lint
